import { prisma } from "../utils/db";
import { computeTrainingLoad } from "../utils/trainingLoad";
import { computeHeartRateCurve } from "../utils/heartRateCurve";
import { extractGpsTrack } from "../utils/gpsTrack";
import { extractLaps } from "../utils/laps";
import {
  computePowerZoneTime,
  computeHeartRateZoneTime,
} from "../utils/zoneTime";

export default defineEventHandler(async (event) => {
  const session = await requireUserSession(event);
  const userId = session.user.id;

  const formData = await readMultipartFormData(event);
  const fitFile = formData?.find((item) => item.name === "file");

  if (!fitFile) {
    throw createError({ statusCode: 400, message: "No file received" });
  }

  // ── 1. Limite dimensione: 25MB (i file .fit reali raramente superano i 5-10MB)
  const MAX_SIZE_BYTES = 25 * 1024 * 1024;
  if (fitFile.data.length > MAX_SIZE_BYTES) {
    throw createError({
      statusCode: 400,
      message: `File too large. Maximum allowed size is 25MB. Your file is ${(fitFile.data.length / (1024 * 1024)).toFixed(1)}MB.`,
    });
  }

  // ── 2. Validazione estensione dichiarata
  const filename = (fitFile.filename ?? "").toLowerCase();
  const isZip = filename.endsWith(".zip");
  const isFit = filename.endsWith(".fit");

  if (!isFit && !isZip) {
    throw createError({
      statusCode: 400,
      message: "Invalid file type. Only .fit and .zip files are accepted.",
    });
  }

  // ── 3. Validazione magic bytes (firma binaria reale del file)
  // Un file .fit ha sempre ".FIT" nei byte 8-11 (0x2E 0x46 0x49 0x54)
  // Un file .zip ha sempre "PK" nei byte 0-1 (0x50 0x4B)
  function validateMagicBytes(buffer: Buffer, declaredIsZip: boolean): boolean {
    if (declaredIsZip) {
      // ZIP magic: PK (0x50 0x4B)
      return buffer.length >= 4 && buffer[0] === 0x50 && buffer[1] === 0x4b;
    } else {
      // FIT magic: byte 8-11 = ".FIT" (0x2E 0x46 0x49 0x54)
      return (
        buffer.length >= 12 &&
        buffer[8] === 0x2e && // .
        buffer[9] === 0x46 && // F
        buffer[10] === 0x49 && // I
        buffer[11] === 0x54
      ); // T
    }
  }

  if (!validateMagicBytes(fitFile.data, isZip)) {
    throw createError({
      statusCode: 400,
      message: isZip
        ? "The file does not appear to be a valid ZIP archive."
        : "The file does not appear to be a valid .fit file. Make sure you are uploading a file generated by your bike computer.",
    });
  }

  // ── 4. Se è uno ZIP: estrai il .fit, poi valida anche quello
  const fitBuffer = extractFitFromUpload(fitFile.data, filename);

  // Valida il .fit estratto dallo zip (potrebbe essere un zip "truffato" con contenuto non-fit)
  if (isZip && !validateMagicBytes(fitBuffer, false)) {
    throw createError({
      statusCode: 400,
      message: "The ZIP file does not contain a valid .fit file.",
    });
  }

  // Da questo punto in poi usa fitBuffer invece di fitFile.data
  const data = await parseFitFile(fitBuffer as any).catch((err: any) => {
    console.error("FIT parsing error:", err);
    throw createError({
      statusCode: 400,
      message: "The .fit file is corrupted or in an unsupported format.",
    });
  });

  const records = data.records || [];
  const session_ = data.sessions?.[0];

  const activity = buildActivitySummary(records, session_);
  const normalizedPower = computeNormalizedPower(records);
  const power_records = computePowerCurve(records);
  const heartRateCurve = computeHeartRateCurve(records);
  const gpsTrack = extractGpsTrack(records);
  const laps = extractLaps(data);

  // "user" va recuperato PRIMA di usarlo in qualunque calcolo successivo
  const user = await prisma.user.findUnique({ where: { id: userId } });
  const ftp = user?.ftp ?? 250;
  const anaerobicThreshold = user?.anaerobicThreshold ?? 160;

  const training_load = computeTrainingLoad({
    normalizedPower,
    ftp,
    durationSeconds: activity.duration,
  });

  const powerZoneTime = computePowerZoneTime(records, ftp);
  const heartRateZoneTime = computeHeartRateZoneTime(
    records,
    anaerobicThreshold,
  );

  const candidateValues: Record<string, number> = {
    peak_power: power_records[0].short_intervals.peak_power,
    "3s_power": power_records[0].short_intervals["3s_power"],
    "5s_power": power_records[0].short_intervals["5s_power"],
    "10s_power": power_records[0].short_intervals["10s_power"],
    "20s_power": power_records[0].short_intervals["20s_power"],
    "30s_power": power_records[0].short_intervals["30s_power"],
    "1min_power": power_records[0].short_intervals["1min_power"],
    "2min_power": power_records[0].short_intervals["2min_power"],
    "3min_power": power_records[0].short_intervals["3min_power"],
    "5min_power": power_records[1].middle_intervals["5min_power"],
    "8min_power": power_records[1].middle_intervals["8min_power"],
    "10min_power": power_records[1].middle_intervals["10min_power"],
    "12min_power": power_records[1].middle_intervals["12min_power"],
    "15min_power": power_records[2].long_intervals["15min_power"],
    "20min_power": power_records[2].long_intervals["20min_power"],
    "30min_power": power_records[2].long_intervals["30min_power"],
    "60min_power": power_records[2].long_intervals["60min_power"],
    distance: Number(activity.distance.toFixed(2)),
    elevation_gain: Math.round(activity.elevation_gain),
    duration: activity.duration,
    kilojoules: activity.kilojoules,
    max_cadence: activity.average_cadence, // TODO: vero max_cadence quando disponibile
    max_speed: Number(activity.max_speed.toFixed(1)),
    max_heartrate: activity.max_heartrate,
    hr_5min: heartRateCurve.hr_5min,
    hr_20min: heartRateCurve.hr_20min,
    hr_1h: heartRateCurve.hr_1h,
  };

  const recordChecks: Array<{
    metricKey: string;
    label: string;
    unit: string;
    newValue: number;
    wouldEnterAt: number | null;
    currentBest: number | null;
  }> = [];

  for (const [metricKey, newValue] of Object.entries(candidateValues)) {
    if (!newValue || newValue <= 0) continue;

    const metricConfig = RECORD_METRICS.find((m) => m.key === metricKey);
    if (!metricConfig) continue;

    const model = getModel(metricKey);
    const existing = await model.findMany({
      where: { userId },
      orderBy: { rank: "asc" },
    });

    const lowerIsBetter = metricConfig.lowerIsBetter;
    const currentBest = existing[0] ? Number(existing[0].value) : null;

    const combined = [
      ...existing.map((e: any) => ({
        value: Number(e.value),
        entryDate: e.entryDate,
        isNew: false,
      })),
      { value: newValue, entryDate: activity.activityDate, isNew: true },
    ];

    combined.sort((a, b) => {
      const primaryDiff = lowerIsBetter ? a.value - b.value : b.value - a.value;
      if (primaryDiff !== 0) return primaryDiff;
      return new Date(b.entryDate).getTime() - new Date(a.entryDate).getTime();
    });

    const top3 = combined.slice(0, 3);
    const positionIndex = top3.findIndex((e) => e.isNew);
    const wouldEnterAt = positionIndex === -1 ? null : positionIndex + 1;

    recordChecks.push({
      metricKey,
      label: metricConfig.label,
      unit: metricConfig.unit,
      newValue,
      wouldEnterAt,
      currentBest,
    });
  }
  return {
    activity: { ...activity, normalized_power: normalizedPower },
    power_records,
    training_load,
    recordChecks,
    gpsTrack,
    laps,
    powerZoneTime,
    heartRateZoneTime,
    filename: fitFile.filename,
  };
});
