interface ActivityData {
  activity: {
    distance: number;
    duration: number;
    average_speed: number;
    max_speed: number;
    average_watts: number;
    max_watts: number;
    normalized_power: number;
    average_heartrate: number;
    max_heartrate: number;
    average_cadence: number;
    elevation_gain: number;
    kilojoules: number;
    kcalories: number;
  };
  training_load?: { tss: number; intensity_factor: number };
  power_records: any[];
}

function formatDuration(totalSeconds: number): string {
  const h = Math.floor(totalSeconds / 3600);
  const m = Math.round((totalSeconds % 3600) / 60);
  return h > 0 ? `${h}h ${m}min` : `${m}min`;
}

function drawBackground(
  ctx: CanvasRenderingContext2D,
  width: number,
  height: number,
) {
  const gradient = ctx.createLinearGradient(0, 0, 0, height);
  gradient.addColorStop(0, "#0b0f14");
  gradient.addColorStop(1, "#0d130f");
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, width, height);
}

function drawHeader(
  ctx: CanvasRenderingContext2D,
  width: number,
  title: string,
) {
  ctx.fillStyle = "#22c55e";
  ctx.font = "bold 22px -apple-system, sans-serif";
  ctx.fillText("BEST RIDE", 48, 64);

  ctx.fillStyle = "#f2f7f4";
  ctx.font = "bold 40px -apple-system, sans-serif";
  ctx.fillText(title, 48, 116);
}

function drawStatBlock(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  label: string,
  value: string,
  unit: string,
) {
  ctx.fillStyle = "#8fa196";
  ctx.font = "15px -apple-system, sans-serif";
  ctx.fillText(label, x, y);

  ctx.fillStyle = "#f2f7f4";
  ctx.font = "bold 34px -apple-system, sans-serif";
  ctx.fillText(value, x, y + 42);

  ctx.fillStyle = "#8fa196";
  ctx.font = "14px -apple-system, sans-serif";
  const valueWidth = ctx.measureText(value).width;
  ctx.font = "bold 34px -apple-system, sans-serif";
  const bigValueWidth = ctx.measureText(value).width;
  ctx.font = "14px -apple-system, sans-serif";
  ctx.fillText(unit, x + bigValueWidth + 6, y + 42);
}

/**
 * Versione COMPLETA per l'allenatore: tutte le metriche disponibili.
 */
export async function generateCoachImage(data: ActivityData): Promise<Blob> {
  const width = 1080;
  const height = 1350;
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d")!;

  drawBackground(ctx, width, height);
  drawHeader(ctx, width, "Ride Report");

  const a = data.activity;
  const t = data.training_load;

  const stats = [
    { label: "DISTANCE", value: a.distance.toFixed(1), unit: "km" },
    { label: "DURATION", value: formatDuration(a.duration), unit: "" },
    { label: "AVG POWER", value: String(a.average_watts), unit: "W" },
    { label: "NORMALIZED POWER", value: String(a.normalized_power), unit: "W" },
    { label: "MAX POWER", value: String(a.max_watts), unit: "W" },
    { label: "AVG SPEED", value: a.average_speed.toFixed(1), unit: "km/h" },
    { label: "MAX SPEED", value: a.max_speed.toFixed(1), unit: "km/h" },
    {
      label: "ELEVATION",
      value: String(Math.round(a.elevation_gain)),
      unit: "m",
    },
    {
      label: "AVG HEART RATE",
      value: String(a.average_heartrate),
      unit: "bpm",
    },
    { label: "MAX HEART RATE", value: String(a.max_heartrate), unit: "bpm" },
    { label: "AVG CADENCE", value: String(a.average_cadence), unit: "rpm" },
    { label: "TSS", value: t ? String(t.tss) : "-", unit: "" },
    {
      label: "INTENSITY FACTOR",
      value: t ? t.intensity_factor.toFixed(2) : "-",
      unit: "",
    },
    { label: "ENERGY", value: String(a.kilojoules), unit: "kJ" },
    { label: "CALORIES", value: String(a.kcalories), unit: "kcal" },
  ];

  const colWidth = (width - 96) / 2;
  let col = 0;
  let row = 0;

  for (const stat of stats) {
    const x = 48 + col * colWidth;
    const y = 200 + row * 90;
    drawStatBlock(ctx, x, y, stat.label, stat.value, stat.unit);

    col++;
    if (col > 1) {
      col = 0;
      row++;
    }
  }

  // Power curve semplificata, disegnata in basso
  drawMiniPowerCurve(
    ctx,
    data.power_records,
    48,
    height - 260,
    width - 96,
    180,
  );

  ctx.fillStyle = "#5c6d63";
  ctx.font = "13px -apple-system, sans-serif";
  ctx.fillText("Generated by Best Ride", 48, height - 30);

  return canvasToBlob(canvas);
}

/**
 * Versione SOCIAL: solo le metriche più "instagrammabili", formato quadrato.
 */
export async function generateSocialImage(data: ActivityData): Promise<Blob> {
  const size = 1080;
  const canvas = document.createElement("canvas");
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext("2d")!;

  drawBackground(ctx, size, size);
  drawHeader(ctx, size, "Ride Complete 🚴");

  const a = data.activity;

  const heroStats = [
    { label: "DISTANCE", value: a.distance.toFixed(1), unit: "km" },
    { label: "DURATION", value: formatDuration(a.duration), unit: "" },
    { label: "AVG POWER", value: String(a.average_watts), unit: "W" },
    {
      label: "ELEVATION",
      value: String(Math.round(a.elevation_gain)),
      unit: "m",
    },
  ];

  const colWidth = (size - 96) / 2;
  heroStats.forEach((stat, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = 48 + col * colWidth;
    const y = 260 + row * 160;
    drawStatBlock(ctx, x, y, stat.label, stat.value, stat.unit);
  });

  ctx.fillStyle = "#22c55e";
  ctx.font = "bold 26px -apple-system, sans-serif";
  ctx.fillText("BEST RIDE", 48, size - 60);

  return canvasToBlob(canvas);
}

function drawMiniPowerCurve(
  ctx: CanvasRenderingContext2D,
  powerRecords: any[],
  x: number,
  y: number,
  width: number,
  height: number,
) {
  if (!powerRecords || powerRecords.length < 3) return;

  const DURATION_META: Record<string, number> = {
    peak_power: 1,
    "3s_power": 3,
    "5s_power": 5,
    "10s_power": 10,
    "20s_power": 20,
    "30s_power": 30,
    "1min_power": 60,
    "2min_power": 120,
    "3min_power": 180,
    "5min_power": 300,
    "8min_power": 480,
    "10min_power": 600,
    "12min_power": 720,
    "15min_power": 900,
    "20min_power": 1200,
    "30min_power": 1800,
    "60min_power": 3600,
  };

  const all = {
    ...powerRecords[0].short_intervals,
    ...powerRecords[1].middle_intervals,
    ...powerRecords[2].long_intervals,
  };
  const points = Object.entries(all)
    .map(([key, watts]) => ({
      seconds: DURATION_META[key],
      watts: watts as number,
    }))
    .filter((p) => p.watts > 0 && p.seconds)
    .sort((a, b) => a.seconds! - b.seconds!);

  if (points.length < 2) return;

  ctx.fillStyle = "#8fa196";
  ctx.font = "14px -apple-system, sans-serif";
  ctx.fillText("POWER CURVE", x, y - 10);

  const logMin = Math.log(points[0]!.seconds!);
  const logMax = Math.log(points[points.length - 1]!.seconds!);
  const maxWatts = Math.max(...points.map((p) => p.watts));

  ctx.beginPath();
  ctx.strokeStyle = "#22c55e";
  ctx.lineWidth = 3;

  points.forEach((p, i) => {
    const px =
      x + ((Math.log(p.seconds!) - logMin) / (logMax - logMin)) * width;
    const py = y + height - (p.watts / maxWatts) * height;
    if (i === 0) ctx.moveTo(px, py);
    else ctx.lineTo(px, py);
  });

  ctx.stroke();
}

function canvasToBlob(canvas: HTMLCanvasElement): Promise<Blob> {
  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) resolve(blob);
      else reject(new Error("Canvas export failed"));
    }, "image/png");
  });
}
